{ pkgs, pkgsLib, ... }:
# Translate a devshell (a derivation produced by `pkgs.mkShell`) into an
# executable script that reproduces the development environment when run.
#
# `pkgs.mkShell` builds a derivation whose output is a dump of the shell
# environment that stdenv set up for the shell.  That dump contains:
#
#   * every variable exported into the shell, including the ones passed
#     directly to `mkShell` (e.g. `FOO = "bar";`),
#   * the computed `PATH`, which already has the `buildInputs` /
#     `nativeBuildInputs` / `packages` on it,
#   * the merged `shellHook`.
#
# This function turns that dump into a runnable script, closely mirroring what
# `nix develop` does with the same information: the recorded environment is
# applied on top of the caller's environment, the build-sandbox locations it
# carries (HOME=/homeless-shelter, TMPDIR=/build, ...) are replaced with the
# caller's values, the devshell's PATH is prepended to the caller's PATH, and
# finally the shellHook is executed before the requested shell is exec'd.
{
  name,
  devshell,
  # Shell to hand control to once the environment is set up.
  shell ? pkgs.bashInteractive,
  # Extra arguments passed to `shell` (e.g. [ "-l" ]).
  shellArgs ? [ ],
  # Extra environment variables to export, taking precedence over the
  # devshell's recorded values.
  extraEnv ? { },
}:
let
  renderedShellArgs = pkgsLib.concatStringsSep " " (map pkgsLib.escapeShellArg shellArgs);
  renderedExtraEnv = pkgsLib.concatStringsSep "\n" (
    pkgsLib.mapAttrsToList (key: value: "export ${key}=${pkgsLib.escapeShellArg (toString value)}") extraEnv
  );
in
pkgs.stdenv.mkDerivation {
  inherit name;

  dontUnpack = true;
  dontConfigure = true;
  dontBuild = true;

  # Makes `pkgsLib.getExe` (and `lib.getExe`) resolve to `bin/${name}`.
  meta.mainProgram = name;

  installPhase = ''
    runHook preInstall

    mkdir -p $out/bin $out/share

    # The mkShell output is a stream of `declare -x NAME="value"` lines that
    # stdenv's `export` builtin recorded, preceded by a human-readable banner.
    # Drop the banner so the result is a valid bash file that can be sourced.
    # (bash renders values containing newlines in the `$'...'` form, so each
    # declaration occupies exactly one line.)
    grep '^declare -x ' ${devshell} > $out/share/devshell-env || true

    cat > $out/bin/${name} <<'DEVSHELL_SCRIPT_EOF'
    #!/usr/bin/env bash
    # Development environment for `${name}`, generated by
    # `sandyFireworksBus.shellScriptOfDevshell` from a `pkgs.mkShell`
    # derivation.

    # The recorded environment comes from a build sandbox, so variables such
    # as HOME, TMPDIR and PWD point at build-time locations.  Remember the
    # caller's values first so they can be restored below.
    declare -A __devshell_saved=()
    for __devshell_var in HOME TMPDIR TEMP TMP TEMPDIR NIX_BUILD_TOP PWD OLDPWD XDG_DATA_DIRS; do
      if [ "''${!__devshell_var+x}" = x ]; then
        __devshell_saved[$__devshell_var]="''${!__devshell_var}"
      fi
    done
    __devshell_saved_PATH="$PATH"

    # Apply the environment recorded by the mkShell derivation.
    # shellcheck disable=SC1091
    . '@devshellEnv@'

    # Restore the caller's build-sandbox-sensitive variables, exactly
    # distinguishing "set to the empty string" from "unset".
    for __devshell_var in HOME TMPDIR TEMP TMP TEMPDIR NIX_BUILD_TOP PWD OLDPWD XDG_DATA_DIRS; do
      if [ "''${__devshell_saved[$__devshell_var]+x}" = x ]; then
        export "$__devshell_var=''${__devshell_saved[$__devshell_var]}"
      else
        unset "$__devshell_var"
      fi
    done

    # The sourced environment set PATH to the devshell's PATH (which already
    # contains the build inputs).  Prepend it to the caller's PATH, the same
    # way `nix develop` does.
    export PATH="$PATH:$__devshell_saved_PATH"

    export IN_NIX_SHELL=impure
    export dontAddDisableDepTrack=1

    # Caller-supplied overrides.
    @extraEnv@

    # Run the (merged) shell hook, if any.  The hook is kept as an environment
    # variable by the mkShell derivation, so it is available after sourcing.
    if [ -n "''${shellHook-}" ]; then
      eval "$shellHook"
    fi

    # POSIX one-shot command invocation: tmux runs the `default-shell' as
    # `<shell> -c <command>' when it executes a shell command in a popup
    # (display-popup uses the default-shell for the popup's command job),
    # and other tools follow the same convention.  The interactive shell
    # configured below may be nushell, which cannot execute POSIX sh
    # command strings (e.g. tmux-grimoire's
    # `tmux select-window ... \; attach-session ...' popup command), so
    # every tmux popup closed immediately after opening.  Delegate `-c'
    # invocations to bash, which implements the POSIX semantics these
    # callers expect; interactive sessions still get the configured shell.
    if [ "''${1-}" = "-c" ]; then
      exec '@posixShell@' -c "''$2"
    fi

    # Hand control over to the requested shell.  If the hook used `exec`
    # (as the headless devshell does to start nushell), this is never reached.
    exec '@shell@' @shellArgs@ "$@"
    DEVSHELL_SCRIPT_EOF

    substituteInPlace $out/bin/${name} \
      --replace-fail '@devshellEnv@' "$out/share/devshell-env" \
      --replace-fail '@shell@' "${pkgsLib.getExe shell}" \
      --replace-fail '@shellArgs@' "${renderedShellArgs}" \
      --replace-fail '@extraEnv@' "${renderedExtraEnv}" \
      --replace-fail '@posixShell@' "${pkgsLib.getExe pkgs.bashInteractive}"

    chmod +x $out/bin/${name}

    runHook postInstall
  '';

  # The original devshell, for introspection.
  passthru.devshell = devshell;
}