[all]
pollingTimeout = 10

[[repositories]]
path = "/home/sieyes/baghdadPlane/flakes/newPeachRampSkateboard"
flakeInputNames = [ ]
push = true
branch = "main"

[[repositories]]
path = "/home/sieyes/baghdadPlane/flakes/mcEatBurg"
flakeInputNames = [ "peachRampSkateboard" ]
push = true
branch = "main"

[[repositories]]
path = "/home/sieyes/baghdadPlane/flakes/nasExitGiScorp"
flakeInputNames = [ "peachRampSkateboard", "mcEatBurg" ]
push = true
branch = "main"

[[repositories]]
path = "/home/sieyes/baghdadPlane/flakes/newFrontArmToPlane"
flakeInputNames = [ "peachRampSkateboard", "mcEatBurg", "nasExitGiScorp" ]
push = true
branch = "main"

[[repositories]]
path = "/home/sieyes/baghdadPlane/flakes/bidGestMirror"
flakeInputNames = [ "peachRampSkateboard", "mcEatBurg", "frontArmToPlane" ]
push = true
branch = "main"

[[repositories]]
path = "/home/sieyes/baghdadPlane/flakes/newThatWaterCharmander"
flakeInputNames = [ "peachRampSkateboard", "frontArmToPlane", "nasExitGiScorp", "mcEatBurg", "bidGestMirror" ]
push = true
branch = "main"

