# ============================================= #
# Start with defaults from the Sensible plugin  #
# --------------------------------------------- #
run-shell /nix/store/iqsm6zlm30wxg3qfmnw4kqsx2jwfxzng-tmuxplugin-sensible-unstable-2017-09-05/share/tmux-plugins/sensible/sensible.tmux
# ============================================= #

set  -g default-terminal "tmux-256color"
set  -g base-index      1
setw -g pane-base-index 1

new-session

set -g status-keys vi
set -g mode-keys   vi

# rebind main key: C-a
unbind C-b
set -g prefix C-a
bind -N "Send the prefix key through to the application" \
  C-a send-prefix

set  -g mouse             off
setw -g aggressive-resize off
setw -g clock-mode-style  24
set  -s escape-time       0
set  -g history-limit     2000

# ============================================= #
# Load plugins with Home Manager                #
# --------------------------------------------- #

# tmuxplugin-gruvbox
# ---------------------

run-shell /nix/store/4vjlnhkjzcmq84g3bsyqrqpm66gy95bj-tmuxplugin-gruvbox-unstable-2022-04-19/share/tmux-plugins/gruvbox/gruvbox-tpm.tmux


# tmuxplugin-resurrect
# ---------------------

run-shell /nix/store/qf8rhrafc7l4vhgzyrbi50c4c8zlrdb4-tmuxplugin-resurrect-unstable-2022-05-01/share/tmux-plugins/resurrect/resurrect.tmux


# tmuxplugin-continuum
# ---------------------
set -g @continuum-restore 'on'
set -g @continuum-save-interval '20' # minutes

run-shell /nix/store/fn256r45gdzp5vk1jdcyijkzw6qln7rv-tmuxplugin-continuum-unstable-2022-01-25/share/tmux-plugins/continuum/continuum.tmux


# tmuxplugin-tilish
# ---------------------
set -g @tilish-default 'main-vertical'
set -g @tilish-easymode 'on'
set -g @tilish-prefix 'C-\'
set -g @tilish-dmenu 'on'

run-shell /nix/store/v6ncmymn4qpca1abn4q889jzpyxj61a8-tmuxplugin-tilish-unstable-2023-09-20/share/tmux-plugins/tilish/tilish.tmux


# tmuxplugin-sysstat
# ---------------------
set -g status-right "#{sysstat_cpu} | #{sysstat_mem} | #{sysstat_swap} | #{sysstat_loadavg} | #[fg=blue]#(echo $USER)#[default]@#H"

run-shell /nix/store/aiv0zwhhxy31qzfwcz0j23i3cn2s19g3-tmuxplugin-sysstat-unstable-2017-12-12/share/tmux-plugins/sysstat/sysstat.tmux

# ============================================= #

# Enable mouse
set -g mouse
set -g mouse on

# horizontal splits
unbind-key |
bind-key | split-window -h

# vertical splits
unbind-key _
bind-key _ split-window

# true color
set -as terminal-overrides ",xterm-kitty,foot:RGB"

# fix cursor shape in neovim
set -ga terminal-overrides ',*:Ss=\E[%p1%d q:Se=\E[2 q'

# swapping panes with arrow keys
unbind-key ^Left
bind-key ^Left swap-pane -U
unbind-key ^Right
bind-key ^Right swap-pane -D
unbind-key ^Up
bind-key ^Up swap-pane -U
unbind-key ^Down
bind-key ^Down swap-pane -D

# use v and y in copy-mode
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection-and-cancel
